### ISSUE TITLE
Missing SEO/metadata

### ISSUE THREAD

**Issue by haydenty** [haydenty/HaydenTy#2]

**Comment by donofriov** [comment]
Hey @haydenty I can add this for you, coming over from Hacktoberfest. Please assign the issue to me.

**Comment by donofriov** [comment]
Do you have a registered domain? If not, I'll just add notes in where certain metadata needs to be changed once you figure out what your domain will be.

**Comment by amitsin6h** [comment]
@haydenty I have fixed this just need to make pull request

**Comment by haydenty** [comment]
@donofriov and @amitsin6h thanks I will take both of your stuff and merge it.
@donofriov I will watch for your PR

Thanks!!

**Comment by amitsin6h** [comment]
@haydenty I can help you make your complete site.

**Comment by haydenty** [comment]
@amitsin6h as of now I don't have too many changes I want made, thanks for offering to help!
