### ISSUE TITLE
Add View Counter to index.html

### ISSUE THREAD

**Issue by haydenty** [haydenty/HaydenTy#5]
I would like to keep track of how many views I am getting but I am not sure whats the best way to implement one of these. Any suggestions/solutions would be greatly appreciated. Is this something standard through my service provider (company I registered my domain through)?

Notes:
I am trying to stay away from setting up an api just for analytics.
Future: would like to know datetime per view.

**Please work off of the Hacktoberfest branch and make all PR to that branch, thanks!**

**Comment by gyanl** [comment]
You could set up Google analytics - it'll give you a lot of information about where your visitors are coming from, what screen sizes they're using, how long sessions last, etc. It's a matter of adding a few lines of js that Google Analytics generates to your project. If you're okay with this, I can set it up and give you access to the dashboard.

**Comment by umer936** [comment]
Yes, Google Analytics is how you should get this information, plus much more.

**Comment by AbhishekBiswal** [comment]
#6 Done. Replace the gaCode value to your actual Google Analytics property code.

**Comment by haydenty** [comment]
@gyanl @umer936  @AbhishekBiswal  thanks really appreciate the quick response to this issue. Thanks for the knowledge transfer I will have to look into Google Analytics some more, sounds like it would be a lot more useful besides just a views total.
